# Generated by Django 3.2.8 on 2022-02-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='calories_food',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='video',
        ),
    ]
