# Generated by Django 3.2.8 on 2022-02-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220211_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tech',
            name='video',
            field=models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
